Move SIPs to Stacksgov
stacks-network/stacks-core pull request #2337
Opened 2021-01-14 04:57 UTC by jcnelson

This PR moves all SIPs to their new home at https://github.com/stacksgov/sips.

2021-01-14 04:59 UTC, kantai commented on sip/README.md
> +This directory formally contained all of the in-progress Stacks Improvement
Typo: formally -> formerly

2021-01-14 14:25 UTC, diwakergupta requested changes
If you've already copied over the SIPs, can we do this post launch?

A lot of places link to SIPs directly (esp. SIP-007) -- instead of deleting, my preference would be to just replace their text with a link to the new corresponding SIP location. After a few weeks of that we can delete the SIPs from here.

2021-01-16 04:25 UTC, lgalabru reviewed
If we already have the new links, should we also update the  `README.md` for this repo?

2021-01-19 16:17 UTC, jcnelson commented
TODO: Add links to the new SIPs where the old SIPs are.

2021-02-22 16:09 UTC, closed without merging

2024-11-24 00:23 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.