Feat/add stacks height to preamble
stacks-network/stacks-core pull request #2961
Opened 2021-12-02 17:39 UTC by pavitthrap

In order to implement the health check endpoint of a node (#2768), the node must have knowledge of its peer's stacks block height. By comparing the height of the tip of the stacks blockchain with that of its startup peers, a node can determine if it is "caught up" with the rest of the network, and is thus "healthy". 

In this PR, I added the canonical stacks tip height to the Preamble, which is sent along with every stacks message sent between peers. The node stores this received information in the `ConversationP2P` object for each peer it is in contact with. 

## Testing 
I updated relevant tests, did not add any new tests.

2021-12-02 17:48 UTC, jcnelson requested changes
I'm sorry, but this approach is basically unworkable.  You can't change the preamble structure, since all peers assume it's a fixed-sized structure with pre-determined byte fields at pre-determined offsets in the buffer.

2021-12-02 18:34 UTC, kantai commented
> I'm sorry, but this approach is basically unworkable. You can't change the preamble structure, since all peers assume it's a fixed-sized structure with pre-determined byte fields at pre-determined offsets in the buffer.

Doesn't that just mean that a form of versioning would be necessary for the preamble structure?

2021-12-02 21:20 UTC, jcnelson commented
A couple things:

* When we originally discussed addressing the problem of communicating the stacks block height between nodes, we agreed to do it via the data plane (https://github.com/blockstack/stacks-blockchain/issues/2822) because doing so would be so much easier than trying to change the p2p wire formats.

* The `Preamble` is not meant to be versioned -- it must be decodable to all nodes. Instead, the `Preamble` struct has an `additional_data` field which is meant to be used as a pointer to an offset in the message payload buffer where to start parsing additional data in a backwards-compatible way (i.e. by adding a trailer to p2p messages beyond the end of the payload).  Then, old nodes would just ignore the trailer, while new nodes would parse it and use it somehow.

This PR does not address #2822 as originally discussed; moreover, even if we wanted to include the Stacks block height in p2p messages (and it's not clear to me that we do), it goes about it in the wrong way.

2021-12-17 00:42 UTC, gregorycoppola reviewed
Thanks, @pavitthrap .

I don't have any new notes, but waiting to see how @jcnelson 's question is resolved.

2022-01-12 16:31 UTC, pavitthrap commented
Closed - will open new PR that adds the stacks height to the HTTP headers.

2022-01-12 16:31 UTC, closed without merging

2024-11-19 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.