Exclude codecov error from CI test pass/fail status
stacks-network/stacks-core pull request #3376
Opened 2022-11-02 22:18 UTC by donpdonp

More than 50% of the failing tests in github pull requests are from the codecov step that happens after cargo test. This patch sets a `codecov-actiion@v2` config setting `fail_ci_if_error` to `false` so that the CI test results reflect the result of the cargo test. 

The codecov upload error reports `POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}` Yet it is inconsistent - the same test for the same PR will have its codecov step work on some CI runs, and fail on others.

2022-11-02 22:19 UTC, donpdonp commented
full error
```
Run codecov/codecov-action@v2
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (20f9c9d78483fce977b6cc39e231a734a23bcd36f4d536bb7355222fb88d02bc  codecov)
==> Running version latest
==> Running version v0.3.2
/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov -n tests::neon_integrations::bitcoind_forking_test -Q github-action-2.1.0 -Z -f ./coverage-output/lcov.info -C 7d22633fefbdc171f3867a8988cb8e05308fb0ed
[2022-11-02T00:59:17.189Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.3.2
[2022-11-02T00:59:17.203Z] ['info'] => Project root located at: /home/runner/work/stacks-blockchain/stacks-blockchain
[2022-11-02T00:59:17.211Z] ['info'] -> No token specified or token is empty
[2022-11-02T00:59:17.222Z] ['info'] Searching for coverage files...
[2022-11-02T00:59:17.326Z] ['info'] => Found 1 possible coverage files:
  ./coverage-output/lcov.info
[2022-11-02T00:59:17.326Z] ['info'] Processing ./coverage-output/lcov.info...
[2022-11-02T00:59:17.548Z] ['info'] Detected GitHub Actions as the CI provider.
[2022-11-02T00:59:17.550Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.3.2&token=*******&branch=feat%2Fnative-segwit-test&build=3373830428&build_url=https%3A%2F%2Fgithub.com%2Fstacks-network%2Fstacks-blockchain%2Factions%2Fruns%2F3373830428&commit=7d22633fefbdc171f3867a8988cb8e05308fb0ed&job=stacks-bitcoin-integration-tests&pr=3357&service=github-actions&slug=stacks-network%2Fstacks-blockchain&name=tests%3A%3Aneon_integrations%3A%3Abitcoind_forking_test&tag=&flags=&parent=
[2022-11-02T00:59:18.543Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov' failed with exit code 255
```

2022-11-03 17:46 UTC, wileyj approved these changes
Adding @jcnelson as a reviewer as well - the changes are fine to me

2022-11-03 17:51 UTC, jcnelson requested changes
We need to find out why uploading the coverage output is failing.  This is something we inspect to verify that tests actually cover the changes we make.  If the error is sporadic, then couldn't we just have the job step re-try uploading the coverage data with exponential back-off for a time?

2022-11-18 19:14 UTC, donpdonp commented
updaing codecov-action from v2 to v3 had no effect. 

the upload errors that were happening on the majority of CI runs are no longer happening. Looking like something internal to the codecov process got fixed.

2022-11-18 19:14 UTC, closed without merging

2024-11-15 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.