`addresses` outputs hexademical public key
stacks-network/stacks-core pull request #3402
Opened 2022-11-16 20:13 UTC by gregorycoppola

### Description
Change the `blockstack-cli` tool so that `addresses` will print out the hexademical public key as well, for applications that need the hexadecimal key version.

### Checklist
- [ ] No testing for command line tool
- [ ] No changelog
- [ ] Update docs for `blockstack-cli`

2022-11-16 20:24 UTC, jcnelson requested changes
Please add test coverage.  In particular, we need to make sure that the public key's hex representation -- compressed vs uncompressed -- aligns with the resulting address.

2022-11-21 16:21 UTC, jcnelson commented
```
#!/usr/bin/env node

const enc = require('@stacks/encryption');
const process = require('process');

const key = process.argv[2];
const publicKey = enc.getPublicKeyFromPrivate(key);
console.log(publicKey);
```

2022-11-21 21:55 UTC, gregorycoppola commented
Sounds like this isn't needed, and so I'll de-prioritize it.

2022-11-21 21:55 UTC, closed without merging

2024-11-15 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.