Round up thresholds using +0.9
stacks-network/stacks-core pull request #4455
Opened 2024-02-29 17:11 UTC by jferrant

@hstove found a bug when operating a single signer with a single key. Essentially the threshold became 0 which causes wsts to panic as it should due to an invalid threshold being provided. @xoloki subsequently pointed out that we actually had a bug in our threshold calculation due to integer arithmatic forcing us to always calculate a threshold "under" our desired amount whenever we had any remainder. This pr forces us to "round up" by adding 0.9 to the result. If any remainder exists, it will force our result over into the next integer amount.

2024-02-29 17:48 UTC, xoloki approved these changes
While I'd prefer a floating point based calculation that explicitly calls `ceil` or some similar function, this is certainly an improvement on what we currently have.

2024-02-29 18:03 UTC, hstove commented
My main concern is how this interacts with the Clarity code for voting on the aggregate key: https://github.com/stacks-network/stacks-core/blob/db9616238dc40ba94ca380238a4b8da8fbc04fbf/stackslib/src/chainstate/stacks/boot/signers-voting.clar#L161-L162

If we round down in Clarity, and up in the signer, what happens?

2024-02-29 18:08 UTC, jferrant commented
> My main concern is how this interacts with the Clarity code for voting on the aggregate key:
> 
> https://github.com/stacks-network/stacks-core/blob/db9616238dc40ba94ca380238a4b8da8fbc04fbf/stackslib/src/chainstate/stacks/boot/signers-voting.clar#L161-L162
> 
> If we round down in Clarity, and up in the signer, what happens?

Nothing bad happens. It means clarity accepts a certain number of votes less than in the wsts calculation side. However, no one will get a result on the wsts side unless they reach the correct threshold. These are ultimately independent thresholds, though its not a bad idea to make them consistent, the clarity one is arbitrary.

2024-02-29 18:15 UTC, kantai approved these changes

2024-02-29 18:29 UTC, hstove commented
Ok, I think I follow. So basically, wsts and the signers are using this threshold to compute a specific threshold that relates to generating a valid signature for that public key, and then Clarity is using its own threshold to determine how many votes are needed to activate it as the aggregate key. That makes sense.

I can imagine some weird edge cases but nothing worth blocking this

2024-02-29 18:30 UTC, hstove approved these changes

2024-02-29 21:53 UTC, xoloki requested changes
LGTM!

2024-02-29 22:29 UTC, merged

2024-11-05 00:20 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.