fix: `target-cpu=native` flag working again
stacks-network/stacks-core pull request #4498
Opened 2024-03-06 21:59 UTC by jbencin

### Description

Pass the flag `target-cpu=native` to `rustc` for local builds and tests for improved performance

### Applicable issues

- #4316 
- #4364: Original commit enabling this flag
- #4489: Broke flag being passed to `rustc` (not sure why)

2024-03-06 22:23 UTC, wileyj commented
this changes quite a lot when considering ti's for 
> Pass the flag target-cpu=native to rustc for local builds and tests for improved performance

what it is goal of this PR?

2024-03-06 22:41 UTC, jbencin commented
> this changes quite a lot when considering ti's for

It touches 12 of files, but it's only adding a single word in 11 of them

> what it is goal of this PR?

It's a few percent perf improvements on local builds. See the discussion on the Slack `#performance` channel. I added this in #4363, but it was broken in #4489

2024-03-06 22:59 UTC, wileyj commented
> > this changes quite a lot when considering ti's for
> 
> It touches 12 of files, but it's only adding a single word in 11 of them
> 
> > what it is goal of this PR?
> 
> It's a few percent perf improvements on local builds. See the discussion on the Slack `#performance` channel. I added this in #4363, but it was broken in #4489

i guess that's my question - you've mentioned "local builds" twice now, but there are only 2 Dockerfiles that *should* ever be used to build locally: `Dockerfile` and `Dockerfle.debian`. the rest are quite specific to PR and release builds. 
 you could make the case to add the change here as well: `./.github/actions/dockerfiles/Dockerfile.debian-source`.

2024-03-06 23:01 UTC, wileyj commented
if #4489 added a regression, wouldn't it be simpler to revert that change vs adding more changes?

2024-03-06 23:22 UTC, wileyj requested changes
requesting changes as a placeholder, i think a call is in order

2024-03-07 19:47 UTC, wileyj commented
@jbencin can PR the `./build-scripts` changes here as well? there is an open PR to start using these files that hasn't merged into `next` yet. 
https://github.com/stacks-network/actions/tree/main/stacks-core/create-source-binary/build-scripts

we can discuss concerns around removing these from the stacks-core repo elsewhere, my main concern is merging this PR, then not having these chagnes in teh `stacks-core/build-scripts` is removed in another open PR

2024-03-07 19:47 UTC, wileyj submitted a review, later dismissed
shipit

2024-03-07 19:49 UTC, wileyj commented
ref: https://github.com/stacks-network/stacks-core/pull/4497

2024-03-12 20:33 UTC, obycode submitted a review, later dismissed
ok, I think this seems fine. 👍

2024-03-13 19:55 UTC, obycode commented
Looks like there are still conflicts here @jbencin

2024-03-13 20:06 UTC, wileyj commented
> Looks like there are still conflicts here @jbencin

it's related to #4497

2024-03-15 17:13 UTC, jcnelson approved these changes

2024-03-18 20:56 UTC, obycode approved these changes

2024-03-20 17:23 UTC, wileyj approved these changes
shipit

2024-03-20 18:03 UTC, merged

2024-11-03 00:23 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.