feat: return any value type from `execute_contract_allow_private`
stacks-network/stacks-core pull request #4520
Opened 2024-03-11 21:37 UTC by hugocaillard

The helper `execute_contract_allow_private` does not allow the private function to return any type and can throw `PublicFunctionMustReturnResponse` if the private function return a non-Response value.

On Clarinet, we get recurrent requests from the community and internal teams to add the ability to call private function in unit tests 

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- N/A Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- N/A New clarity functions have corresponding PR in `clarity-benchmarking` repo
- N/A New integration test(s) added to `bitcoin-tests.yml`

2024-03-11 22:07 UTC, jcnelson requested changes
I think this should be epoch-gated so we don't accidentally use it prior to epoch 2.5

2024-03-12 10:36 UTC, hugocaillard commented
@jcnelson @kantai 
Following your remarks (here and on slack), I pushed a new commit that only have effect is developer-mode (which clarinet uses)
```rs
            else if allow_private && cfg!(feature = "developer-mode") {
                self.commit()?;
                Ok(result)
            }
```

@jcnelson 
> I think this should be epoch-gated so we don't accidentally use it prior to epoch 2.5

Ideally, I'd like to be able to use it for any epoch in simnet

2024-03-13 14:13 UTC, hugocaillard commented
@kantai 

>  as long as its controlled with a compile flag

Right now i'm using the `cfg!` macro, which, as I understand is slightly different from a compile flag (`#[cgf(...)]`). I could use a compile flag instead but it would make the code slightly less readable I think
```rs
    pub fn handle_tx_result(
        &mut self,
        result: Result<Value>,
        allow_private: bool,
    ) -> Result<Value> {
        if let Ok(result) = result {
            if let Value::Response(data) = result {
                if data.committed {
                    self.commit()?;
                } else {
                    self.roll_back()?;
                }
                Ok(Value::Response(data))
            } else {
                #[cfg(feature = "developer-mode")]
                if allow_private {
                    self.commit()?;
                    return Ok(result);
                }
                Err(
                    CheckErrors::PublicFunctionMustReturnResponse(TypeSignature::type_of(&result)?)
                        .into(),
                )
            }
        } else {
            self.roll_back()?;
            result
        }
    }
```

---
    
>  something specifically like allow-private

I'm starting to think that just "allow-private" is confusing. Because it should really be `allow-private-to-return-any-type` (or something like that)

Should I just introduce a flag like "devtools" or "clarinet"? I'm sure I can find tons of usage for such a flag in the future

2024-03-13 14:38 UTC, kantai commented
> Right now i'm using the cfg! macro, which, as I understand is slightly different from a compile flag (#[cgf(...)]). I could use a compile flag instead but it would make the code slightly less readable I think

Ah, yes, the `cfg!` macro is fine here. I agree it results in more readable code.

> Should I just introduce a flag like "devtools" or "clarinet"? I'm sure I can find tons of usage for such a flag in the future

Yes -- either works.

2024-03-13 15:44 UTC, hugocaillard commented
Done @kantai, I went for "devtools"

2024-03-13 15:56 UTC, kantai approved these changes
LGTM!

2024-03-13 16:00 UTC, jcnelson submitted a review, later dismissed
LGTM, but before merging, please add a comment to `handle_tx_result()` to indicate that `allow_private` is ignored unless the node is compiled with the `devtools` feature (the comment should include the line that they'd have to add to their `Cargo.toml` or the build flags to pass to `cargo`).

2024-03-13 16:36 UTC, hugocaillard commented
Done @jcnelson

2024-03-14 15:07 UTC, kantai approved these changes
LGTM!

2024-03-14 16:29 UTC, jcnelson approved these changes

2024-03-15 14:16 UTC, merged

2024-11-03 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.