chore: fix typos
stacks-network/stacks-core pull request #4608
Opened 2024-03-30 03:15 UTC by xiaoxianBoy

### Description
fix some typos

2024-03-30 03:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stacks-network/stacks-core?pullRequest=4608) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stacks-network/stacks-core?pullRequest=4608) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stacks-network/stacks-core?pullRequest=4608) it.</sub>

2024-03-30 06:05 UTC, xoloki approved these changes
LGTM

2024-04-01 15:18 UTC, wileyj commented
This needs to be rebased against `develop`

2024-04-01 15:18 UTC, wileyj requested changes
rebase agains develop

2026-02-20 15:57 UTC, jcnelson commented
Closing due to inactivity

2026-02-20 15:57 UTC, closed without merging