Reward cycle length was being incorrectly stored as reward phase length
stacks-network/stacks-core pull request #4629
Opened 2024-04-03 13:26 UTC by jferrant

Sometimes regtest would stall on boot with the following messages:
	
2024-04-02, 05:32:20.104 PM	
[signer_runloop] Received a new burnchain block height (117) in the prepare phase of the next reward cycle (6). Checking for signer registration...
2024-04-02, 05:32:20.057 PM	
[signer_runloop] Received a new burnchain block height (117) in the prepare phase of the next reward cycle (5). Checking for signer registration.

This made me realize something was up with the reward cycle info or prepare phase calculation. Was accidentally storing the full reward cycle length but calling it the reward phase length and then adding and subtracting the prepare phase length again. This should fix the problem. 

Fixes https://github.com/stacks-network/stacks-core/issues/4630

2024-04-03 13:43 UTC, obycode requested changes
Can we add some unit tests that would have caught this issue?

2024-04-03 13:45 UTC, kantai reviewed
Yep -- this is definitely a bug and a corresponding fix!

Can you add an assertion to one of the end to end signers tests that would have caught this?

2024-04-03 19:06 UTC, kantai approved these changes

2024-04-03 19:37 UTC, jcnelson approved these changes

2024-04-04 01:18 UTC, obycode approved these changes

2024-04-04 01:18 UTC, obycode commented
Sorry, didn't realize this was waiting on me.

2024-04-04 01:39 UTC, merged

2024-11-03 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.