Chore: remove infinite loop in signer during tests
stacks-network/stacks-core pull request #5259
Opened 2024-10-01 14:13 UTC by kantai

### Description

This PR removes an infinite loop in the signer when `cfg!(test)` is active. The rationale for this is that signer integration tests often stop the `stacks-node` threads (via panic, asserts, etc.) on failure before they stop the signer threads. I think this leads to a situation where a test failure loops indefinitely, which in the CI prevents logs from appearing, making diagnosing CI failures and flaky tests _very_ difficult.

This PR also removes the first block push invocation -- if the first push in the loop succeeds, there's no need to repush.

2024-10-01 14:33 UTC, jferrant approved these changes

2024-10-01 14:34 UTC, jferrant requested changes
There is another infinite loop where post_block is called. If you could add that change there too, it would be great!

2024-10-01 21:08 UTC, wileyj commented on .github/workflows/bitcoin-tests.yml
> +        uses: stacks-network/actions/stacks-core/run-tests@feat/no-capture-2
merged, can be reverted to `main`

2024-10-02 14:33 UTC, jferrant approved these changes

2024-10-02 14:58 UTC, wileyj approved these changes
lgtm

2024-10-02 15:30 UTC, merged

2024-10-25 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.