Fix/5267
stacks-network/stacks-core pull request #5270
Opened 2024-10-03 18:14 UTC by jcnelson

Fixes #5267 by making it so that an idle downloader can be assigned to a different peer.

2024-10-03 18:23 UTC, obycode approved these changes
Nice! LGTM

2024-10-03 18:30 UTC, kantai commented on stackslib/src/net/download/nakamoto/download_state_machine.rs
> +        test_debug!("new tenure_block_ids: {:?}", &tenure_block_ids);
Can you consolidate into a single `test_debug!` line?

2024-10-03 18:35 UTC, kantai submitted a review, later dismissed

2024-10-03 19:04 UTC, hstove requested changes
Pretty much LGTM, just a note about the `_` prefix. You also have some compilation errors in `net/tests/downloader/nakamoto` if you haven't seen that yet

2024-10-03 19:04 UTC, hstove commented on stackslib/src/net/download/nakamoto/tenure_downloader.rs
> +            NakamotoTenureDownloadState::GetTenureStartBlock(_block_id, _start_request_time) => {
Nit here (and a few other similar lines) - don't prefix with `_` if it gets used

2024-10-03 19:31 UTC, hstove approved these changes

2024-10-03 19:35 UTC, obycode approved these changes

2024-10-04 02:33 UTC, merged

2024-10-25 00:22 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.