Include `tenure_height` in `/new_block` event payload
stacks-network/stacks-core pull request #5333
Opened 2024-10-18 14:41 UTC by zone117x

Part of https://github.com/hirosystems/explorer/issues/1624 and https://github.com/hirosystems/stacks-blockchain-api/issues/2124

Adds a `tenure_height` (AKA `coinbase_height`) to the `/new_block` event payload.

In epoch2.x this is the same value as `block_height`.

2024-10-18 16:43 UTC, jcnelson approved these changes

2024-10-18 16:49 UTC, hstove requested changes
I haven't fully reviewed this, but I don't think that integration test is a good place for this, because there aren't any nakamoto blocks (ie without TenureChange) produced. `check_block_info` might be a better place for this - just basically take the same assertions you have and move them to the end of that test?

2024-10-18 20:52 UTC, kantai approved these changes

2024-10-18 23:57 UTC, hstove approved these changes
LGTM!

2024-10-19 00:24 UTC, merged

2024-10-27 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.