feat: event emitter will now emit new_txid in-case a tx replaces another
stacks-network/stacks-core pull request #5381
Opened 2024-10-24 19:24 UTC by usagi32

This extra information is required by an issue in the blockchain-api [here ](https://github.com/hirosystems/stacks-blockchain-api/pull/2141)and [here](https://github.com/hirosystems/stacks-blockchain-api/issues/1813).

Event emitter will now give to the api node which transaction replaced another.

2024-10-24 19:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stacks-network/stacks-core?pullRequest=5381) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stacks-network/stacks-core?pullRequest=5381) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stacks-network/stacks-core?pullRequest=5381) it.</sub>

2024-10-24 19:44 UTC, jferrant approved these changes

2024-10-24 19:45 UTC, jferrant commented
I could be wrong, but I think this may need to be opened against develop, not master.

2024-10-24 19:57 UTC, usagi32 commented
@jferrant yes didn't know it existed.

2024-11-08 16:24 UTC, jcnelson approved these changes
This LGTM, pending CI passes.  Thanks @usagi32!

2024-11-08 20:36 UTC, hstove commented
@usagi32 you'll have to fix some of the formatting errors before CI runs tests - you can see these by running `cargo fmt-stacks`

2024-11-21 03:41 UTC, obycode submitted a review, later dismissed
LGTM!

2024-11-21 15:08 UTC, jcnelson submitted a review, later dismissed
LGTM. Thanks @usagi32!

2024-11-21 15:22 UTC, hstove submitted a review, later dismissed

2024-11-21 15:23 UTC, hstove commented
Ah, unfortunately there's a new compilation error, assuming from after merging in develop.

2024-11-25 14:53 UTC, jbencin commented
Fixed build errors and merged latest `develop`

2024-11-25 16:07 UTC, hstove submitted a review, later dismissed

2024-11-25 17:02 UTC, obycode approved these changes
LGTM!

2024-11-25 17:04 UTC, obycode requested changes
Could we add a changelog entry for this?

2024-12-18 20:02 UTC, hstove approved these changes

2024-12-18 21:04 UTC, obycode commented on CHANGELOG.md
> +- When a transaction is dropped due to replace-by-fee, the `/drop_mempool_tx` event observer payload now includes `new_txid`, which is the transaction that replaced this dropped transaction. When a t
Can you moved this under "Changed"?

2024-12-20 01:10 UTC, obycode submitted a review, later dismissed
LGTM!

2024-12-20 01:11 UTC, obycode commented
Oh, it's not running the CI jobs because the last commit only changed a markdown file. Looks like we need some adjustments to the CI rules.

2024-12-20 14:56 UTC, hstove commented
@obycode I think it's something to do with me pushing to this forked branch, I'm not sure. Maybe I'll need to open a new PR...

2024-12-20 15:00 UTC, obycode commented
Looks like merging develop was enough to get it to trigger, so maybe my Markdown theory was correct?

2024-12-20 15:01 UTC, obycode approved these changes

2024-12-20 15:05 UTC, closed without merging

2024-12-20 15:05 UTC, hstove commented
Closing, reponed as https://github.com/stacks-network/stacks-core/pull/5605

2024-12-28 00:17 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.