Add tenure_extend_timestamp to Block Response Reject and Accept messages
stacks-network/stacks-core pull request #5466
Opened 2024-11-15 21:19 UTC by jferrant

Needed to complete https://github.com/stacks-network/stacks-core/issues/5434

2024-11-15 21:20 UTC, jferrant commented on stacks-signer/src/tests/conf/signer-0.toml
> -endpoint = "localhost:30000"
Changed this to make config to str test pass.

2024-11-15 21:42 UTC, hstove requested changes
This needs to be backwards compatible - right now it'll fail if the payload doesn't have the timestamp. I think there's already a unit test with fixtures for backwards compatibility

2024-11-15 22:04 UTC, jferrant commented
> This needs to be backwards compatible - right now it'll fail if the payload doesn't have the timestamp. I think there's already a unit test with fixtures for backwards compatibility

I mean I can easily make this default fill the timestamp with 0 if not found. Not sure that is considered backwards compatible enough. I don't actually see why this has to be backwards compatible though. It would of course require signers to upgrade, by why does this need to be backwards compatible?

2024-11-15 22:05 UTC, jferrant commented
> > This needs to be backwards compatible - right now it'll fail if the payload doesn't have the timestamp. I think there's already a unit test with fixtures for backwards compatibility
> 
> I mean I can easily make this default fill the timestamp with 0 if not found. Not sure that is considered backwards compatible enough. I don't actually see why this has to be backwards compatible though. It would of course require signers to upgrade, by why does this need to be backwards compatible? I say this because we don't ever backprocess block responses.

2024-11-15 22:08 UTC, obycode commented
> I don't actually see why this has to be backwards compatible though.

Since we are doing this without a hard fork, miners that upgrade should be able to talk to signers that have not upgraded, and vice versa.

2024-11-15 22:09 UTC, jferrant commented
> > I don't actually see why this has to be backwards compatible though.
> 
> Since we are doing this without a hard fork, miners that upgrade should be able to talk to signers that have not upgraded, and vice versa.

haha I just answered this in my own response to Hank right before I saw this XD

2024-11-16 20:20 UTC, hstove approved these changes
LGTM! Should we merge this into a broader feature branch? This PR itself is probably fine to merge into develop, but with other PRs we'll probably want some other base branch.

2024-11-17 14:22 UTC, obycode commented
> LGTM! Should we merge this into a broader feature branch? This PR itself is probably fine to merge into develop, but with other PRs we'll probably want some other base branch.

Yeah, that's a good point. Let's merge everything into `feat/time-based-tenure-extend` until we're ready.

2024-11-17 14:27 UTC, obycode approved these changes
LGTM

2024-11-18 16:12 UTC, merged

2024-11-26 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.