Tenure extend changelog
stacks-network/stacks-core pull request #5550
Opened 2024-12-09 20:04 UTC by obycode

Sorry, I could've sworn we already had this in #5530.

2024-12-09 20:05 UTC, jferrant submitted a review, later dismissed

2024-12-09 20:06 UTC, wileyj requested changes
we'll need to pull in the 3.1 changelog (that PR is still open)

2024-12-09 20:26 UTC, wileyj approved these changes
shipit!

2024-12-09 20:50 UTC, aldur approved these changes

2024-12-09 21:22 UTC, merged

2024-12-17 00:19 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.