[node] Add "connections.block_proposal_max_age_secs" and ignore block proposals more than the configured amount
stacks-network/stacks-core pull request #5552
Opened 2024-12-10 18:44 UTC by jferrant

Closes https://github.com/stacks-network/stacks-core/issues/5439

2024-12-16 19:41 UTC, obycode approved these changes
LGTM! Just one minor comment.

2024-12-16 19:41 UTC, obycode commented on stackslib/src/net/api/postblock_proposal.rs
> +                .wrapping_add(network.get_connection_opts().block_proposal_max_age_secs)
Shouldn't really matter, but would a `saturating_add` make more sense here?

2024-12-16 19:59 UTC, jcnelson approved these changes

2024-12-16 20:27 UTC, obycode approved these changes
👍

2024-12-16 20:30 UTC, hstove requested changes
I think you forgot to add `block_proposal_max_age_secs` to `ConnectionOptionsFile` (with related code to pass into `ConnectionOptions`).

(This is such an easy thing to forget, it'd be great if we had more of a serde_toml approach or something to make this cleaner and less footgunable)

2024-12-16 21:30 UTC, jcnelson approved these changes

2024-12-16 21:49 UTC, obycode commented
> I think you forgot to add `block_proposal_max_age_secs` to `ConnectionOptionsFile` (with related code to pass into `ConnectionOptions`).
> 
> (This is such an easy thing to forget, it'd be great if we had more of a serde_toml approach or something to make this cleaner and less footgunable)

💯 Totally agree!

2024-12-16 21:52 UTC, obycode approved these changes

2024-12-16 22:44 UTC, hstove submitted a review, later dismissed

2024-12-17 03:16 UTC, hstove commented
Hmm, `tests::signer::v0::idle_tenure_extend_active_mining` is failing

2024-12-17 15:49 UTC, jferrant commented
> Hmm, `tests::signer::v0::idle_tenure_extend_active_mining` is failing

Both idle_tenure_extend_active_mining and miner_recovers_when_broadcast_block_delay_across_tenures_occurs pass locally, but this PR is the first time i have seen these fail which is stressing me out.

2024-12-18 20:53 UTC, obycode approved these changes

2025-01-02 22:44 UTC, jcnelson commented on CHANGELOG.md
> +- Added configuration option `connections.block_proposal_max_age_secs` to prevent processing stale block proposals
Can we label this by what toml header it goes under?  i.e. `[connection_options]`?

2025-01-02 22:45 UTC, jcnelson approved these changes

2025-01-07 16:06 UTC, jferrant commented on CHANGELOG.md
> +- Added configuration option `connections.block_proposal_max_age_secs` to prevent processing stale block proposals
Yes. Will update.

2025-01-08 15:29 UTC, hstove approved these changes

2025-01-08 19:12 UTC, obycode approved these changes

2025-01-09 15:01 UTC, merged

2025-01-17 00:17 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.