Fix/ci no tests full genesis test
stacks-network/stacks-core pull request #5576
Opened 2024-12-16 19:04 UTC by jferrant

2024-12-16 19:11 UTC, jcnelson approved these changes

2024-12-16 19:30 UTC, hstove requested changes

2024-12-16 19:52 UTC, wileyj commented on .github/workflows/stacks-core-tests.yml
> +          - tests::neon_integrations::bitcoind_integration_test
in fact, i'd say we remove that entire step in the workflow - it's been failing recently anyways

2024-12-16 19:59 UTC, wileyj commented on .github/workflows/stacks-core-tests.yml
> +          - tests::neon_integrations::bitcoind_integration_test
@jferrant  - i've removed it and pushed

2024-12-16 20:11 UTC, jferrant commented on .github/workflows/stacks-core-tests.yml
> +          - tests::neon_integrations::bitcoind_integration_test
Yes I noticed this, but I assumed it was kept separately due to the test coverage call after it. @wileyj if this is redundant, let me know.

2024-12-16 20:11 UTC, jferrant commented on .github/workflows/stacks-core-tests.yml
> +          - tests::neon_integrations::bitcoind_integration_test
Oh I see you have already dealt with @wileyj  :P

2024-12-16 20:30 UTC, obycode submitted a review, later dismissed
LGTM! Tests are failing? Just delete the tests -- problem solved! 😅

2024-12-16 21:01 UTC, obycode commented
Are the jobs not running because of something wrong with this change?

2024-12-16 21:33 UTC, obycode commented
> Are the jobs not running because of something wrong with this change?

I just pushed a change that I think resolves that. 🤞

2024-12-16 21:58 UTC, obycode approved these changes

2024-12-16 22:43 UTC, hstove approved these changes

2024-12-17 01:18 UTC, merged

2024-12-25 00:17 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.