Fix int_plus_one warnings
stacks-network/stacks-core pull request #5626
Opened 2024-12-31 18:13 UTC by jferrant

2024-12-31 23:25 UTC, jbencin commented on stackslib/src/chainstate/stacks/index/trie.rs
> +        let new_leaf_path = cursor.path[(if cursor.tell() < cursor.path.len() {
Instead of an awkward `if` statement inside square brackets, how about:

```rust
std::cmp::min(cursor.tell() + 1, cursor.path.len())
```

2024-12-31 23:26 UTC, jbencin submitted a review, later dismissed

2025-01-02 19:39 UTC, obycode approved these changes
🙏

2025-01-02 22:51 UTC, jcnelson submitted a review, later dismissed

2025-01-03 13:31 UTC, obycode submitted a review, later dismissed
lgtm

2025-01-03 20:22 UTC, jcnelson commented on stackslib/src/chainstate/stacks/index/trie.rs
> +            cursor.path[std::cmp::min(cursor.tell() + 1, cursor.path.len())..].to_vec();
Don't you want `std::cmp::min(cursor.tell(), cursor.path.len())`?

2025-01-03 20:22 UTC, jcnelson requested changes
See comment

2025-01-03 20:54 UTC, jbencin commented on stackslib/src/chainstate/stacks/index/trie.rs
> +            cursor.path[std::cmp::min(cursor.tell() + 1, cursor.path.len())..].to_vec();
I don't think so, look at the previous `if` statement, it can never index by `cursor.tell()`, only `cursor.tell() + 1`

2025-01-03 20:55 UTC, jbencin submitted a review, later dismissed

2025-01-04 01:41 UTC, jferrant commented on stackslib/src/chainstate/stacks/index/trie.rs
> +            cursor.path[std::cmp::min(cursor.tell() + 1, cursor.path.len())..].to_vec();
Yeah so the prior if check would make sure that the `cursor.tell() < cursor.path.len()` before indexing always by `cusor.tell() + 1` as Jeff mentions. So I think what I have is equivalent.

2025-01-10 15:18 UTC, jbencin approved these changes

2025-01-10 22:07 UTC, obycode approved these changes

2025-02-08 03:16 UTC, merged

2025-02-16 00:19 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.